name: Run Python script every 10 minutes

# Schedule to run every 10 minutes
on:
  schedule:
    - cron: "* * * * *"

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run Python script
      run: python Botssy.py
